job-repository-type=jdbc
db-url=${JBERET_DATABASE_URL:jdbc:postgresql://localhost:5434/postgres_postgres_workload}
db-user=${JBERET_DATABASE_USER:oxide_batch_workload}
db-password=${JBERET_DATABASE_PASSWORD:oxide_batch_workload}
db-table-prefix=jberet.
thread-pool-type=fixed
thread-pool-core-size=3
